name: oxenfox
favicon: null
layout_spectrum: 0.75862
typography_spectrum: 0.56305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9c8c0'
    - '#859aab'
    - '#364854'
    - '#be7e58'
    - '#965d32'
  brandStrength: 0.13734197686426342
  lightness: 0.09278079634532332
  saturation: 0.7428663522005081
  rhythmicContrast: 0.7712500628549606
purpose: []
